docs: add port review template & revamp submission guidelines
catppuccin/catppuccin pull request #1937
Opened 2023-02-22 03:33 UTC by sgoudham

## Motivation

As we recently switched over to GitHub discussions for our port requests, we have noticed a slight inefficiency in the new process. Ports are sometimes fully themed and ready to review before a discussion has been created. This is, of course, completely okay but results in a wasted step of creating the discussion and transferring it to an issue instantly. 

## Proposal 

Create two types of port requests...

1. **Port Suggestions**
   - Renamed from Port Requests, this is the same process as we currently have for discussions. However, this will now be restricted to only **WIP ports and suggestions/ideas for ports to be included within Catppuccin**.
3. **Port Reviews**
   - New issue template on the repository itself, ports that are **already themed and ready for review** should be raised here instead of the GitHub discussion.

We hope that this isn't too confusing for our existing maintainers and new maintainers to come. 

P.S Sorry for the reformatting changes :sweat_smile:

## TODO List before/during merging

- [ ] Figure out the URL for `port-review` to reference within `port-suggestion.md` and `port-creation.md`
- [ ] Rename `port-requests` to `port-suggestions` in GitHub discussions

2023-02-22 08:07 UTC, ghostx31 commented
Great PR Hammy! The document changes look good. 

As for the URL for `port-review`, we can probably take some idea from `catppuccin/cli` which opens the issue template with the URL: `https://github.com/catppuccin/cli/issues/new?assignees=&labels=bug&template=bug_report.md&title=`.

2023-02-22 09:54 UTC, nekowinston reviewed
Looks good, some quick thoughts since we're reworking this again.

2023-02-22 09:54 UTC, nekowinston commented on .github/ISSUE_TEMPLATE/port-review.yml
> +labels: ["port request", "ready for review"]
Should we update our label name to reflect the "port review" term too?
I'm also unsure about adding "ready for review" by default for every newly created review issue.

2023-02-22 09:54 UTC, nekowinston commented on .github/ISSUE_TEMPLATE/port-review.yml
> +          required: true
Here's an idea:
By checking *Submission Guidelines*, contributors agree to the wording in [Port Creation/Submission](https://github.com/catppuccin/catppuccin/blob/main/docs/port-creation.md#submission):
> **All ports** should conform to our [CODE OF CONDUCT](https://github.com/catppuccin/.github/blob/main/CODE_OF_CONDUCT.md) and we, the staff team, ...

And by this *Code of Conduct* section they agree to follow it themselves.

Maybe we should add a "Maintenance" section in our port creation doc? :thinking:
We could reduce this to just a single checkbox, and also state that we really *can't and won't expect people to maintain it forever*. Currently, we have this weird blurry line where if a port is new, I feel hesitant to directly push onto the repo without a PR.
If we make it clear that they're submitting the repository for something like a co-maintenance with the staff team (since we've also added staff to every single public repo), seeing us commit chore/hotfix pushes ([reformatting the README, for example](https://github.com/catppuccin/drracket/pull/3)) would hopefully be seen as normal, and not staff taking over the repo.

2023-02-22 09:54 UTC, nekowinston commented on docs/port-creation.md
> +  `windows-files`).
I forgot @Pocco81's exact wording on Discord, but didn't he want `lower-kebab-case` mentioned here? I'd like to see the term used as well.
Another thing that comes to mind is:
> must be the simplest version of the app's name

This led to a few weird repo names, like [mc](https://github.com/catppuccin/mc)... What's `mc` without clicking? Minecraft? Minio Client? Midnight Commander? :joy:
[windows-files](https://github.com/catpppuccin/windows-files) on the other hand, seems to be known as *Files*, but apparently we felt the need to be explicit with the naming here (and rightly so IMO).
We could probably be fine just saying to stick to lower-kebab-case.

I just realized that only the formatting got changed here, but I wanted to raise this discussion anyhow.

2023-02-22 12:49 UTC, Pocco81 commented on docs/port-creation.md
> +  `windows-files`).
Yes. `lower-kebab-case`.

> like [mc](https://github.com/catppuccin/mc)... What's mc without clicking? ... ...Midnight Commander?

What about:

> must be the simplest version of the **program**'s name without falling into oversimplification (e.g. `minecraft` -> `mc`) and niche-obscurity (e.g. something only followers of the program might understand)

2023-02-22 19:31 UTC, sgoudham commented on .github/ISSUE_TEMPLATE/port-review.yml
> +labels: ["port request", "ready for review"]
My initial thoughts are that I agree. I want to ensure we have our labelling documented or at-least visualised in a way that could benefit both staff and the community. I believe @backwardspy was interested in looking at this, potentially using [insert documentation tool that I've forgotten the name of] :smile:

Also, I'd personally like to get to a point where any issue raised on the repository is either `meta` or just `awaiting review` -> `ready to transfer` I think that starts with moving the current `draft availables` from the issues over to discussions as we did previously. 

Thoughts?

2023-02-22 19:32 UTC, sgoudham commented on .github/ISSUE_TEMPLATE/port-review.yml
> +labels: ["port request", "ready for review"]
In the short term, I think we should remove the `port request` label and just stick an `awaiting review` label onto new port review issues

2023-02-22 19:37 UTC, sgoudham commented on .github/ISSUE_TEMPLATE/port-review.yml
> +          required: true
Yeah, this sounds good, I like the idea of a maintenance section on the repository re-iterating the notion that staff will also play a part in any changes that may be made in the future.

2023-02-22 19:52 UTC, nekowinston commented on .github/ISSUE_TEMPLATE/port-review.yml
> +labels: ["port request", "ready for review"]
That makes sense. I like the idea of defaulting to port requests, and having "meta" for the org-wide issues :+1:

2023-02-22 23:47 UTC, backwardspy commented
@catppuccin/staff we have put together a couple of options for visualising the port creation workflow [here](https://github.com/catppuccin/catppuccin/blob/docs/port-review/docs/port-creation.md#option-1-sequence-diagram) and [here](https://github.com/catppuccin/catppuccin/blob/docs/port-review/docs/port-creation.md#option-2-flow-chart). these are of course rough drafts at this stage.

interested in your thoughts on how useful this will be, and whether another tool might be better (excalidraw et al.) we started with mermaid for ease of maintenance, however this does place restrictions on styling & layout.

2023-02-23 00:16 UTC, sgoudham commented on .github/ISSUE_TEMPLATE/port-review.yml
> +labels: ["port request", "ready for review"]
Just to clarify, you're okay with me removing the `port request` label from the port-review template and renaming the current `ready for review` label to `awaiting review`? 

I was just a little bit confused about what you meant by 

> defaulting to port requests

2023-02-23 00:29 UTC, nekowinston commented on docs/port-creation.md
> +```
Another idea
```mermaid
stateDiagram-v2
  idea: Port idea
  idea --> choice
  choice: Are you willing to make the port?

  choice --> author: Yes
  author: Work on a draft for a port
  author --> staff_mention


  choice --> request: No
  request: Open a Port Request discussion
  request_picked_up: Somebody starts work on a draft
  request --> request_picked_up
  request_picked_up --> staff_mention

  staff_mention: Mention @staff when the port is ready for review
  staff_mention --> review
  review: Review period
  review --> port_adoption

  note right of review
    Community feedback
  end note

  port_adoption: Port adoption
  ```

2023-02-23 00:38 UTC, nekowinston commented on .github/ISSUE_TEMPLATE/port-review.yml
> +labels: ["port request", "ready for review"]
I meant that we could also get away with having no label for the review period. If a label applies to all issues that aren't `meta` or `waiting on author`, does it really need a label?

2023-02-23 00:46 UTC, sgoudham commented on .github/ISSUE_TEMPLATE/port-review.yml
> +labels: ["port request", "ready for review"]
Hmm yeah, @backwardspy and I talked about that too, just thought it'd be nice in contrast to having `meta` issues. Probably just personal preference on my part for pretty colours :P 

Defaulting to nothing sounds good :+1:

2023-02-23 01:50 UTC, sgoudham commented
Tidied up the docs as per PR comments, curious about what people think of the new [port-creation.md](https://github.com/catppuccin/catppuccin/blob/44749016fac7c25421dde138905a90c9a1a0fc2a/docs/port-creation.md) 

Tried to get everything underneath the #Submission heading and link off to it. Worth mentioning that the visualisation diagram is still a WIP!

2023-02-23 02:07 UTC, alaidriel commented
I found the diagram by @nekowinston to be the easiest to follow because in the other two it didn't seem as clear where the workflow starts for people who already have completed themes that are ready for review.

2023-02-23 07:53 UTC, ghostx31 commented
@backwardspy I found winston's diagram easier to follow. Maybe we might add it to `port-creation.md`?
Also, about `port-creation.md`:
- https://github.com/catppuccin/catppuccin/blob/98e67a4b1925cffc63532719f72cf66c4fd2573b/docs/port-creation.md?plain=1#L160
	We should also ask to add the app's name to the topics.

2023-02-23 09:15 UTC, backwardspy commented on docs/port-creation.md
> +```
yeah i like that, good idea!

2023-02-23 21:03 UTC, nullishamy commented
It would be nice if staff-transferred discussions and 'port reviews' were standardised to be the same / similar. Would further reduce friction and confusion for people reading the issues.

2023-02-23 21:14 UTC, sgoudham commented
Really great point you've raised there @nullishamy

In the short term, I think there'll be a burden on staff to ensure that transferred issues are reformatted into the `port-review` template. In the longer term, I'd love the existence of a GitHub bot to automate the manual processes that are manual... one day :P

2023-02-24 00:55 UTC, sgoudham commented
Just one thing that I noticed in your port workflow diagram, I was under the following impression

> 1. **Port Requests** (GitHub Discussions)
>    - This is the same process we currently have for discussions. However, this will now be restricted to only **WIP ports and suggestions/ideas for ports to be included within Catppuccin**.
> 2. **Port Reviews** (GitHub Issues)
>    - New issue template on the repository itself, ports that are **already themed and ready for review** should be raised here instead of the GitHub discussion.

The diagram seems to suggest that for port requests, we actually don't want WIP ports at all? Is that correct? @nekowinston

2023-02-24 01:37 UTC, ghostx31 approved these changes

2023-02-24 09:32 UTC, backwardspy commented
> Just one thing that I noticed in your port workflow diagram, I was under the following impression
> 
> > 1. **Port Requests** (GitHub Discussions)
> >    
> >    * This is the same process we currently have for discussions. However, this will now be restricted to only **WIP ports and suggestions/ideas for ports to be included within Catppuccin**.
> > 2. **Port Reviews** (GitHub Issues)
> >    
> >    * New issue template on the repository itself, ports that are **already themed and ready for review** should be raised here instead of the GitHub discussion.
> 
> The diagram seems to suggest that for port requests, we actually don't want WIP ports at all? Is that correct? @nekowinston

this is tricky. there are really three cases, while the graph currently only shows two.

1. you want a port, and you don't want to make it.
2. you want a port, and you want to make it
3. you've already made a port

we cover #1 and #3 in the graph, but not really #2. perhaps the question "are you willing to make it" should instead be "have you made it already".

i think we definitely want to encourage the creation of a discussion, regardless of who will work on the draft.

2023-02-24 12:49 UTC, nekowinston commented
> The diagram seems to suggest that for port requests, we actually don't want WIP ports at all? Is that correct? @nekowinston

Ah no, sorry, that's not what I meant. I made the `stateDiagram` as a draft to show off the graph layout, so consider it a draft and not a finished graphic.

> this is tricky. there are really three cases, while the graph currently only shows two.

```mermaid
stateDiagram-v2
  choice: Are you willing to make the port?
  choice --> author: Yes
  author: Work on a draft for a port
  author --> feedback_needed
  feedback_needed: Do you want feedback while porting?
  feedback_needed --> author_done : No
  feedback_needed --> request: Yes
  author_done: Once a port is finished, create an issue, requesting review from @staff
  choice --> request: No
  request: Open a Port Request discussion
  request --> author_done
  ```

Do we want something like this then?
Who do we want to create the issues from a discussion? Staff or the authors?

Here's how I understand what we're trying to achieve with rewording this, using @backwardspy's list:

> 1. you want a port, and you don't want to make it.
> 2. you want a port, and you want to make it
> 3. you've already made a port

1. Raise a discussion, for people to pick up
2. Raise a discussion to talk about the details of making it easy to maintain, etc.
3. Fast-tracking current org members so that they only have to create an issue

What we could also add (we're assuming that we're starting out at a port idea):
- Pointing people who want to work on something, but don't have an idea, to the discussions for inspiration

2023-02-24 13:40 UTC, backwardspy commented
it seems to me that by changing the question at the start, we can keep the flow simple while covering (i think!) all cases:

```mermaid
stateDiagram-v2
  idea: You have an idea for a port
  idea --> choice

  choice: Have you already completed a draft?
  choice --> draft_complete: Yes
  choice --> request: No

  request: Open a Port Request discussion
  request --> request_picked_up
  
  request_picked_up: You or somebody else works on a draft
  request_picked_up --> request_complete

  request_complete: The draft is completed to your liking
  request_complete --> draft_complete
  
  draft_complete: Create a port review issue
  draft_complete --> review

  review: Review period
  review --> port_adoption

  note right of review
    Community feedback
  end note

  port_adoption: Port adoption
```

thoughts?

2023-02-26 03:38 UTC, nekowinston commented
Yeah I think that would cover everything. Way easier to read than more branches in the graph.

2023-02-26 05:20 UTC, nekowinston requested changes

2023-02-26 05:20 UTC, nekowinston commented on docs/port-creation.md
> +the staff team!
Isn't this paragraph restating the first sentence of the previous one?

2023-02-26 05:20 UTC, nekowinston commented on docs/port-creation.md
> +Please get in touch with us if that is the case with your work!
I would phrase it along these lines:
> However, there are [exceptions to this rule](https://github.com/search?q=org%3Acatppuccin+-license%3Amit). Please get in touch with us, if the application you're theming has licensing restrictions, or your work is a derivative of a stricter license (e.g. [cursors](https://github.com/catppuccin/cursors#info)).

2023-02-27 00:18 UTC, sgoudham commented on docs/port-creation.md
> +the staff team!
Oh whoops, I was re-wording this to be the paragraph above and clearly forgot to take it out. 
Will delete it :+1:

2023-02-27 02:08 UTC, nekowinston approved these changes

2023-02-27 11:05 UTC, backwardspy approved these changes

2023-02-27 14:54 UTC, taka0o approved these changes

2023-02-27 16:05 UTC, sgoudham commented
Before I merge this in, are you folks happy if I transfer the existing `draft-available` issues into discussions? 

@nekowinston @backwardspy @ghostx31 @taka0o

2023-02-27 16:12 UTC, ghostx31 commented
Sure, it's a yes from me.

2023-02-27 22:48 UTC, sgoudham commented
Drafts moved over, merging now. Thanks, everyone for the comments and feedback throughout this! :heart:

2023-02-27 22:56 UTC, merged