docs: update badges
catppuccin/catppuccin pull request #2360
Opened 2024-04-09 10:59 UTC by uncenter

Updates the badges to use Catppuccin colors (not sure what colors it was even using before, didn't seem to come from any of the palettes) and removes the WCAG one... seeing as latte isn't passing that yet xD.

2024-04-11 17:21 UTC, andreasgrafen commented
Oh, right.. They might be using a previous version of the colours and just never got updated.
The License one in the footer also seems to have an incorrect colour. We probably should change that too then.

2024-04-14 17:44 UTC, uncenter commented
@andreasgrafen is there anything else I need to do here?

2024-04-14 19:53 UTC, sgoudham requested changes
I liked having the release badge tbh, I think it would be nice to keep it

2024-04-14 19:53 UTC, sgoudham commented on README.md
> +	<a href="https://github.com/catppuccin/template/issues"><img src="https://img.shields.io/github/issues/catppuccin/catppuccin?colorA=363a4f&colorB=f5a97f&style=for-the-badge"></a>
```suggestion
  <a href="https://github.com/catppuccin/catppuccin/stargazers"><img src="https://img.shields.io/github/stars/catppuccin/catppuccin?colorA=363a4f&colorB=b7bdf8&style=for-the-badge"></a>
	<a href="https://github.com/catppuccin/catppuccin/issues"><img src="https://img.shields.io/github/issues/catppuccin/catppuccin?colorA=363a4f&colorB=f5a97f&style=for-the-badge"></a>
```

2024-04-14 20:23 UTC, uncenter commented
> I liked having the release badge too tbh, I think it would be nice to keep it

Sounds good. I went with green for the badge color, let me know if you want a different color.

2024-04-14 20:52 UTC, sgoudham commented on README.md
> +	<a href="https://discord.com/servers/907385605422448742"><img src="https://img.shields.io/discord/907385605422448742?style=for-the-badge&logo=discord&color=c6a0f6&logoColor=cad3f5&labelColor=363a4f"
Did you intend to remove the `&logo=...` for the ones besides discord ? I actually didn't mind them and thought it was a nice touch.

2024-04-14 20:53 UTC, uncenter commented on README.md
> +	<a href="https://discord.com/servers/907385605422448742"><img src="https://img.shields.io/discord/907385605422448742?style=for-the-badge&logo=discord&color=c6a0f6&logoColor=cad3f5&labelColor=363a4f"
Yes I did. We don't use them on any other badges across the organization.

2024-04-14 20:58 UTC, sgoudham commented on README.md
> +	<a href="https://discord.com/servers/907385605422448742"><img src="https://img.shields.io/discord/907385605422448742?style=for-the-badge&logo=discord&color=c6a0f6&logoColor=cad3f5&labelColor=363a4f"
I felt like the icons gave it more character, can we make an exception for ctp/ctp? :D

2024-04-15 16:46 UTC, uncenter commented on README.md
> +	<a href="https://discord.com/servers/907385605422448742"><img src="https://img.shields.io/discord/907385605422448742?style=for-the-badge&logo=discord&color=c6a0f6&logoColor=cad3f5&labelColor=363a4f"
Sure! Maybe we can use some better icons lol than stealing Starship's? I'll make a commit now and let me know what you think :)

2024-04-15 16:52 UTC, uncenter commented on README.md
> +	<a href="https://discord.com/servers/907385605422448742"><img src="https://img.shields.io/discord/907385605422448742?style=for-the-badge&logo=discord&color=c6a0f6&logoColor=cad3f5&labelColor=363a4f"
Added! I went with Phosphor Icons' Discord icon here so it matches the rest as well.

2024-04-15 16:53 UTC, uncenter commented
Also I just realized we'll probably want to update the badges at https://github.com/catppuccin/.github/blob/main/profile/README.md as well once this is merged.

2024-04-15 18:02 UTC, uncenter commented on README.md
> +	<a href="https://discord.com/servers/907385605422448742"><img src="https://img.shields.io/discord/907385605422448742?style=for-the-badge&logo=discord&color=c6a0f6&logoColor=cad3f5&labelColor=363a4f"
> Oh, custom Icons is a nice idea. Now… getting into nitpicking; I think solid icons would look better than the outlines ones as right now the icons seem to suffer a bit in terms of legibility.

Sounds good, I agree. I've updated the icons with what you've provided.

> And regarding Discord specifically.. I really don't like Phospor's Discord icon as it's … well _not_ the Discord icon. I personally would opt for a proper one here even tho it would be a different icon set; but I'm also happy to accept the Phosphor icon if y'all prefer it. c: Oh, and yes.. the same can be said about the GitHub icon, but it's far more in line with the original octo cat i'd say.

I'm with you on that it doesn't really match Discord's branding but for consistency I think it is best with the Phosphor Icon.

2024-04-16 01:42 UTC, andreasgrafen commented on README.md
> +	<a href="https://discord.com/servers/907385605422448742"><img src="https://img.shields.io/discord/907385605422448742?style=for-the-badge&logo=discord&color=c6a0f6&logoColor=cad3f5&labelColor=363a4f"
mmh.. really torn here. if it weren't for it being brand icons i'd opt for all phosphor in a heartbeat. it just looks better. **but** i feel like it makes it easier to spot what the badges are about when the actual logos are in place. do you have any thoughts on this @sgoudham?

&nbsp;

<p align="center">
  <a href="https://github.com/catppuccin/catppuccin/stargazers"><img src="https://img.shields.io/github/stars/catppuccin/catppuccin?colorA=363a4f&colorB=b7bdf8&style=for-the-badge&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTYgMjU2Ij4KPHBhdGggZD0iTTIzNS4yNCw4NC4zOGwtMjguMDYsMjMuNjgsOC41NiwzNS4zOWExMy4zNCwxMy4zNCwwLDAsMS01LjA5LDEzLjkxLDEzLjU0LDEzLjU0LDAsMCwxLTE1LC42OUwxNjQsMTM5bC0zMS42NSwxOS4wNmExMy41MSwxMy41MSwwLDAsMS0xNS0uNjksMTMuMzIsMTMuMzIsMCwwLDEtNS4xLTEzLjkxbDguNTYtMzUuMzlMOTIuNzYsODQuMzhhMTMuMzksMTMuMzksMCwwLDEsNy42Ni0yMy41OGwzNi45NC0yLjkyLDE0LjIxLTMzLjY2YTEzLjUxLDEzLjUxLDAsMCwxLDI0Ljg2LDBsMTQuMjEsMzMuNjYsMzYuOTQsMi45MmExMy4zOSwxMy4zOSwwLDAsMSw3LjY2LDIzLjU4Wk04OC4xMSwxMTEuODlhOCw4LDAsMCwwLTExLjMyLDBMMTguMzQsMTcwLjM0YTgsOCwwLDAsMCwxMS4zMiwxMS4zMmw1OC40NS01OC40NUE4LDgsMCwwLDAsODguMTEsMTExLjg5Wm0tLjUsNjEuMTlMMzQuMzQsMjI2LjM0YTgsOCwwLDAsMCwxMS4zMiwxMS4zMmw1My4yNi01My4yN2E4LDgsMCwwLDAtMTEuMzEtMTEuMzFabTczLTEtNTQuMjksNTQuMjhhOCw4LDAsMCwwLDExLjMyLDExLjMybDU0LjI4LTU0LjI4YTgsOCwwLDAsMC0xMS4zMS0xMS4zMloiIHN0eWxlPSJmaWxsOiAjQ0FEM0Y1OyIvPgo8L3N2Zz4="></a>
  <a href="https://github.com/catppuccin/catppuccin/releases/"><img src="https://img.shields.io/github/v/release/catppuccin/catppuccin?colorA=363a4f&colorB=a6da95&style=for-the-badge&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTYgMjU2Ij4KPHBhdGggZD0iTTIxNiwxMDR2OGE1Ni4wNiw1Ni4wNiwwLDAsMS00OC40NCw1NS40N0EzOS44LDM5LjgsMCwwLDEsMTc2LDE5MnY0MGE4LDgsMCwwLDEtOCw4SDEwNGE4LDgsMCwwLDEtOC04VjIxNkg3MmE0MCw0MCwwLDAsMS00MC00MEEyNCwyNCwwLDAsMCw4LDE1MmE4LDgsMCwwLDEsMC0xNiw0MCw0MCwwLDAsMSw0MCw0MCwyNCwyNCwwLDAsMCwyNCwyNEg5NnYtOGEzOS44LDM5LjgsMCwwLDEsOC40NC0yNC41M0E1Ni4wNiw1Ni4wNiwwLDAsMSw1NiwxMTJ2LThhNTguMTQsNTguMTQsMCwwLDEsNy42OS0yOC4zMkE1OS43OCw1OS43OCwwLDAsMSw2OS4wNywyOCw4LDgsMCwwLDEsNzYsMjRhNTkuNzUsNTkuNzUsMCwwLDEsNDgsMjRoMjRhNTkuNzUsNTkuNzUsMCwwLDEsNDgtMjQsOCw4LDAsMCwxLDYuOTMsNCw1OS43NCw1OS43NCwwLDAsMSw1LjM3LDQ3LjY4QTU4LDU4LDAsMCwxLDIxNiwxMDRaIiBzdHlsZT0iZmlsbDogI0NBRDNGNTsiLz4KPC9zdmc+"></a>
	<a href="https://github.com/catppuccin/catppuccin/issues"><img src="https://img.shields.io/github/issues/catppuccin/catppuccin?colorA=363a4f&colorB=f5a97f&style=for-the-badge&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTYgMjU2Ij4KPHBhdGggZD0iTTIxNiwzMlYxOTJhOCw4LDAsMCwxLTgsOEg3MmExNiwxNiwwLDAsMC0xNiwxNkgxOTJhOCw4LDAsMCwxLDAsMTZINDhhOCw4LDAsMCwxLTgtOFY1NkEzMiwzMiwwLDAsMSw3MiwyNEgyMDhBOCw4LDAsMCwxLDIxNiwzMloiIHN0eWxlPSJmaWxsOiAjQ0FEM0Y1OyIvPgo8L3N2Zz4="></a>
	<a href="https://discord.com/servers/907385605422448742"><img src="https://img.shields.io/discord/907385605422448742?style=for-the-badge&color=c6a0f6&labelColor=363a4f&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTYgMjU2Ij4KPHBhdGggZD0iTTI0Ny41MSwxNzQuMzksMjE4LDU4YTE2LjA4LDE2LjA4LDAsMCwwLTEzLTExLjg4bC0zNi4wNi01LjkyYTE2LjIyLDE2LjIyLDAsMCwwLTE4LjI2LDExLjg4bC0uMjEuODVhNCw0LDAsMCwwLDMuMjcsNC45MywxNTUuNjIsMTU1LjYyLDAsMCwxLDI0LjQxLDUuNjIsOC4yLDguMiwwLDAsMSw1LjYyLDkuNyw4LDgsMCwwLDEtMTAuMTksNS42NCwxNTUuNCwxNTUuNCwwLDAsMC05MC44LS4xLDguMjIsOC4yMiwwLDAsMS0xMC4yOC00LjgxLDgsOCwwLDAsMSw1LjA4LTEwLjMzLDE1Ni44NSwxNTYuODUsMCwwLDEsMjQuNzItNS43Miw0LDQsMCwwLDAsMy4yNy00LjkzbC0uMjEtLjg1QTE2LjIxLDE2LjIxLDAsMCwwLDg3LjA4LDQwLjIxTDUxLDQ2LjEzQTE2LjA4LDE2LjA4LDAsMCwwLDM4LDU4TDguNDksMTc0LjM5YTE1Ljk0LDE1Ljk0LDAsMCwwLDkuMDYsMTguNTFsNjcsMjkuNzFhMTYuMTcsMTYuMTcsMCwwLDAsMjEuNzEtOS4xbDMuNDktOS40NWE0LDQsMCwwLDAtMy4yNy01LjM1LDE1OC4xMywxNTguMTMsMCwwLDEtMjguNjMtNi4yLDguMiw4LjIsMCwwLDEtNS42MS05LjY3LDgsOCwwLDAsMSwxMC4yLTUuNjYsMTU1LjU5LDE1NS41OSwwLDAsMCw5MS4xMiwwLDgsOCwwLDAsMSwxMC4xOSw1LjY1LDguMTksOC4xOSwwLDAsMS01LjYxLDkuNjgsMTU3Ljg0LDE1Ny44NCwwLDAsMS0yOC42Miw2LjIsNCw0LDAsMCwwLTMuMjcsNS4zNWwzLjQ5LDkuNDVhMTYuMTgsMTYuMTgsMCwwLDAsMjEuNzEsOS4xbDY3LTI5LjcxQTE1Ljk0LDE1Ljk0LDAsMCwwLDI0Ny41MSwxNzQuMzlaTTkyLDE1MmExMiwxMiwwLDEsMSwxMi0xMkExMiwxMiwwLDAsMSw5MiwxNTJabTcyLDBhMTIsMTIsMCwxLDEsMTItMTJBMTIsMTIsMCwwLDEsMTY0LDE1MloiIHN0eWxlPSJmaWxsOiAjQ0FEM0Y1OyIvPgo8L3N2Zz4="></a>
</p>
<p align="center">
  <a href="https://github.com/catppuccin/catppuccin/stargazers"><img src="https://img.shields.io/github/stars/catppuccin/catppuccin?colorA=363a4f&colorB=b7bdf8&style=for-the-badge&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTYgMjU2Ij4KPHBhdGggZD0iTTIzNS4yNCw4NC4zOGwtMjguMDYsMjMuNjgsOC41NiwzNS4zOWExMy4zNCwxMy4zNCwwLDAsMS01LjA5LDEzLjkxLDEzLjU0LDEzLjU0LDAsMCwxLTE1LC42OUwxNjQsMTM5bC0zMS42NSwxOS4wNmExMy41MSwxMy41MSwwLDAsMS0xNS0uNjksMTMuMzIsMTMuMzIsMCwwLDEtNS4xLTEzLjkxbDguNTYtMzUuMzlMOTIuNzYsODQuMzhhMTMuMzksMTMuMzksMCwwLDEsNy42Ni0yMy41OGwzNi45NC0yLjkyLDE0LjIxLTMzLjY2YTEzLjUxLDEzLjUxLDAsMCwxLDI0Ljg2LDBsMTQuMjEsMzMuNjYsMzYuOTQsMi45MmExMy4zOSwxMy4zOSwwLDAsMSw3LjY2LDIzLjU4Wk04OC4xMSwxMTEuODlhOCw4LDAsMCwwLTExLjMyLDBMMTguMzQsMTcwLjM0YTgsOCwwLDAsMCwxMS4zMiwxMS4zMmw1OC40NS01OC40NUE4LDgsMCwwLDAsODguMTEsMTExLjg5Wm0tLjUsNjEuMTlMMzQuMzQsMjI2LjM0YTgsOCwwLDAsMCwxMS4zMiwxMS4zMmw1My4yNi01My4yN2E4LDgsMCwwLDAtMTEuMzEtMTEuMzFabTczLTEtNTQuMjksNTQuMjhhOCw4LDAsMCwwLDExLjMyLDExLjMybDU0LjI4LTU0LjI4YTgsOCwwLDAsMC0xMS4zMS0xMS4zMloiIHN0eWxlPSJmaWxsOiAjQ0FEM0Y1OyIvPgo8L3N2Zz4="></a>
  <a href="https://github.com/catppuccin/catppuccin/releases/"><img src="https://img.shields.io/github/v/release/catppuccin/catppuccin?colorA=363a4f&colorB=a6da95&style=for-the-badge&logo=data:image/svg+xml;base64,PHN2ZyByb2xlPSJpbWciIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+R2l0SHViPC90aXRsZT48cGF0aCBkPSJNMTIgLjI5N2MtNi42MyAwLTEyIDUuMzczLTEyIDEyIDAgNS4zMDMgMy40MzggOS44IDguMjA1IDExLjM4NS42LjExMy44Mi0uMjU4LjgyLS41NzcgMC0uMjg1LS4wMS0xLjA0LS4wMTUtMi4wNC0zLjMzOC43MjQtNC4wNDItMS42MS00LjA0Mi0xLjYxQzQuNDIyIDE4LjA3IDMuNjMzIDE3LjcgMy42MzMgMTcuN2MtMS4wODctLjc0NC4wODQtLjcyOS4wODQtLjcyOSAxLjIwNS4wODQgMS44MzggMS4yMzYgMS44MzggMS4yMzYgMS4wNyAxLjgzNSAyLjgwOSAxLjMwNSAzLjQ5NS45OTguMTA4LS43NzYuNDE3LTEuMzA1Ljc2LTEuNjA1LTIuNjY1LS4zLTUuNDY2LTEuMzMyLTUuNDY2LTUuOTMgMC0xLjMxLjQ2NS0yLjM4IDEuMjM1LTMuMjItLjEzNS0uMzAzLS41NC0xLjUyMy4xMDUtMy4xNzYgMCAwIDEuMDA1LS4zMjIgMy4zIDEuMjMuOTYtLjI2NyAxLjk4LS4zOTkgMy0uNDA1IDEuMDIuMDA2IDIuMDQuMTM4IDMgLjQwNSAyLjI4LTEuNTUyIDMuMjg1LTEuMjMgMy4yODUtMS4yMy42NDUgMS42NTMuMjQgMi44NzMuMTIgMy4xNzYuNzY1Ljg0IDEuMjMgMS45MSAxLjIzIDMuMjIgMCA0LjYxLTIuODA1IDUuNjI1LTUuNDc1IDUuOTIuNDIuMzYuODEgMS4wOTYuODEgMi4yMiAwIDEuNjA2LS4wMTUgMi44OTYtLjAxNSAzLjI4NiAwIC4zMTUuMjEuNjkuODI1LjU3QzIwLjU2NSAyMi4wOTIgMjQgMTcuNTkyIDI0IDEyLjI5N2MwLTYuNjI3LTUuMzczLTEyLTEyLTEyIiBmaWxsPSIjQ0FEM0Y1Ii8+PC9zdmc+"></a>
	<a href="https://github.com/catppuccin/catppuccin/issues"><img src="https://img.shields.io/github/issues/catppuccin/catppuccin?colorA=363a4f&colorB=f5a97f&style=for-the-badge&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTYgMjU2Ij4KPHBhdGggZD0iTTIxNiwzMlYxOTJhOCw4LDAsMCwxLTgsOEg3MmExNiwxNiwwLDAsMC0xNiwxNkgxOTJhOCw4LDAsMCwxLDAsMTZINDhhOCw4LDAsMCwxLTgtOFY1NkEzMiwzMiwwLDAsMSw3MiwyNEgyMDhBOCw4LDAsMCwxLDIxNiwzMloiIHN0eWxlPSJmaWxsOiAjQ0FEM0Y1OyIvPgo8L3N2Zz4="></a>
	<a href="https://discord.com/servers/907385605422448742"><img src="https://img.shields.io/discord/907385605422448742?style=for-the-badge&color=c6a0f6&labelColor=363a4f&logo=data:image/svg+xml;base64,PHN2ZyByb2xlPSJpbWciIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+RGlzY29yZDwvdGl0bGU+PHBhdGggZD0iTTIwLjMxNyA0LjM2OThhMTkuNzkxMyAxOS43OTEzIDAgMDAtNC44ODUxLTEuNTE1Mi4wNzQxLjA3NDEgMCAwMC0uMDc4NS4wMzcxYy0uMjExLjM3NTMtLjQ0NDcuODY0OC0uNjA4MyAxLjI0OTUtMS44NDQ3LS4yNzYyLTMuNjgtLjI3NjItNS40ODY4IDAtLjE2MzYtLjM5MzMtLjQwNTgtLjg3NDItLjYxNzctMS4yNDk1YS4w [...]

2024-04-16 02:10 UTC, uncenter commented on README.md
> +	<a href="https://discord.com/servers/907385605422448742"><img src="https://img.shields.io/discord/907385605422448742?style=for-the-badge&logo=discord&color=c6a0f6&logoColor=cad3f5&labelColor=363a4f"
Ah I agree with you actually. I'll switch to Simple Icons for GitHub and Discord. 🫡

2024-04-16 02:34 UTC, andreasgrafen approved these changes

2024-04-16 11:07 UTC, sgoudham requested changes
Badges look very nice! Just suggested a tiny change to actually point to the latest release.

2024-04-16 11:07 UTC, sgoudham commented on README.md
> +  <a href="https://github.com/catppuccin/catppuccin/releases/"><img src="https://img.shields.io/github/v/release/catppuccin/catppuccin?colorA=363a4f&colorB=a6da95&style=for-the-badge&logo=github&logo
```suggestion
  <a href="https://github.com/catppuccin/catppuccin/releases/latest"><img src="https://img.shields.io/github/v/release/catppuccin/catppuccin?colorA=363a4f&colorB=a6da95&style=for-the-badge&logo=github&logoColor=cad3f5"></a>
```

2024-04-16 14:34 UTC, sgoudham approved these changes

2024-04-16 14:38 UTC, andreasgrafen commented
LGTM!

2024-04-16 14:43 UTC, merged