docs(contributing): fix broken link
catppuccin/catppuccin pull request #2487
Opened 2024-07-30 20:06 UTC by somerand0mcat

## 🔧 What does this fix? 🔧
fixes a link thats going to a folder (or a branch) that doesn't exist anymore

2024-07-30 20:08 UTC, uncenter requested changes

2024-07-30 20:08 UTC, uncenter commented on CONTRIBUTING.md
> +- Create a [topic branch](https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows) on your fork for your
```suggestion
- Create a [topic branch](https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows#_topic_branch) on your fork for your
```

2024-07-30 21:27 UTC, uncenter approved these changes

2024-08-05 13:43 UTC, sgoudham approved these changes

2024-08-05 13:43 UTC, merged

2024-08-12 11:34 UTC, somerand0mcat commented
hey @sgoudham would you mind telling me some feedback on how to improve my [recent userstyles PRs](https://github.com/catppuccin/userstyles/pull/1183) and make it better?

2024-08-12 14:01 UTC, uncenter commented
> @sgoudham btw would you mind telling me some feedback on how to improve my [recent userstyles PRs](https://github.com/catppuccin/userstyles/pull/1183) and make it better?

Hammy is on the core team, and we on the userstyles staff team have given you plenty of feedback. I'm not sure what else Hammy could offer you here - and this isn't even a userstyles PR! 😅

2024-08-12 14:04 UTC, somerand0mcat commented
> Hammy is on the core team, and we on the userstyles staff team have given you plenty of feedback. I'm not sure what else Hammy could offer you here - and this isn't even a userstyles PR! 😅

i mean.. why not

2024-08-12 14:06 UTC, somerand0mcat commented
> Hammy is on the core team, and we on the userstyles staff team have given you plenty of feedback. I'm not sure what else Hammy could offer you here - and this isn't even a userstyles PR! 😅

i mean.. why not

2024-08-12 14:10 UTC, uncenter commented
> > Hammy is on the core team, and we on the userstyles staff team have given you plenty of feedback. I'm not sure what else Hammy could offer you here - and this isn't even a userstyles PR! 😅
> 
> i mean.. why not

Since you are needlessly pinging a core team member for feedback on a userstyles issue. And since you have been struggling to integrate our comments over your PRs, I'm not sure "more feedback" is helpful for you or worth the time by Hammy.

2024-08-12 14:13 UTC, somerand0mcat commented
> Since you are needlessly pinging a core team member for feedback on a userstyles issue. Not to mention you have been struggling to integrate our comments over your PRs- I'm not sure "more feedback" is helpful for you or worth the time to give from Hammy.

maybe i'll just stop asking hammy for feedback ig

> struggling to integrate our comments over your PRs

comments like what, better classnames?

2024-08-12 14:22 UTC, uncenter commented
> maybe i'll just stop asking hammy for feedback ig

Yes, this is what I said. Another suggestion is you don't need to restate others's feedback every time it is given, just thumbs up and move on.

> comments like what, better classnames?

Again, I've given you plenty of feedback recently (yes, better classnames!) and *this is not a userstyles PR*. Willing to discuss this further but I'm not sure what you are looking for? We had this exact same discussion less than 48 hours ago on a related PR.