Added Zen Browser port
catppuccin/catppuccin pull request #2577
Opened 2024-10-22 04:31 UTC by IAmJafeth

Closes https://github.com/catppuccin/catppuccin/issues/2544

2024-10-22 11:05 UTC, uncenter requested changes

2024-10-22 11:05 UTC, uncenter commented on resources/ports.yml
> +  -browser:
```suggestion
  zen-browser:
```

2024-10-22 11:05 UTC, uncenter commented on resources/ports.yml
> +    icon: zen-browser
```suggestion
```
There is no icon for this brand yet on https://simpleicons.org/ where these are sourced from.

2024-10-22 11:05 UTC, uncenter commented on resources/ports.yml
> +    color: sapphire
They seem to pretty much use crust/text in terms of branding colors 🤔

2024-10-23 00:50 UTC, sgoudham approved these changes
Thanks!

2024-10-23 00:50 UTC, merged